# This yaml template pipeline will deploy Virtual network

parameters:
  - name: azureSubscription
    type: string
    displayName: Service Connection name (Azure)
  - name: resourceGroupName
    type: string
    displayName: Resourcegroup name for the Virtual Network
  - name: vNetName
    type: string
    displayName: Virtual Networkname
  - name: location
    type: string
    displayName: Location for Virtual Network

steps:
- task: AzurePowerShell@5
  displayName: Create - Virtual Network
  condition: succeeded()
  inputs:
    azureSubscription: ${{parameters.azureSubscription }}
    ScriptType: 'FilePath'
    ScriptPath: 'Infrastructure/AzureResourceIaC/VirtualNetwork/Scripts/Create-VirtualNetwork.ps1'
    ScriptArguments:  -ResourceGroupName ${{parameters.resourceGroupName }}
             -VNetName '${{parameters.vNetName }}'
             -Location '${{parameters.location }}'
    azurePowerShellVersion: 'LatestVersion'