## This master pipleine will deploy the full azure infrastructure for the XXXXXXX
trigger: none

name: XXXX Azure Infrastructure Deployment

parameters:
  - name: azureSubscription
    type: string
    displayName: Service Connection name (Azure)
    default: amitabhdas-azure
  - name: resourceGroupName
    type: string
    displayName: Resourcegroup name for the Web App
    default: RGCloud
  - name: webAppName
    type: string
    displayName: Web app name
    default: mydddmmooaap1
  - name: location
    type: string
    displayName: Location for Web App
    default: eastus2
  - name: appServicePlanSku
    type: string
    displayName: AppServicePlanSku type (ex- 'Free', 'Shared', 'Basic', 'Standard', 'Premium', 'Dynamic')
    default: Standard
  - name: appServicePlanSkuCode
    type: string
    displayName: AppServicePlanSkuCode type (ex- "F1", "D1", "B1", "B2", "B3",  "S1",  "S2",  "S3",  "P1", "P2",  "P3",  "P1V2", "P2V2", "P3V2", "Y1")
    default: S2

stages:

- stage: Create_WebAPP
  displayName: Create_WebAPP
  jobs:
  - job:
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: AzureResourceIaC/WebApp/Pipeline/create-webapp.yaml
